version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LetsG000000
      POSTGRES_DB: csvdb
    # volumes:
    #     - ./postgres-data:/var/lib/postgresql/data
    # ports:
    #   - "15432:5432"
