version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LetsG000000
      POSTGRES_DB: csvdb
    ports:
      - "5432:5432"
    # volumes:
    #     - ./postgres-data:/var/lib/postgresql/data
    # ports:
    #   - "15432:5432"
